# Generated by Django 4.1 on 2023-07-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_homeaboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='passport_back',
            field=models.FileField(blank=True, null=True, upload_to='passport'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='passport_front',
            field=models.FileField(blank=True, null=True, upload_to='passport'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='PP'),
        ),
    ]
